### ISSUE TITLE
Try to run it on google colab/ jupyter notebook, report error in "final_input = torch.cat((term_NN_out_map[self.root], drug_out), 1)" (line 177 of drugcell_NN.py))

### ISSUE THREAD

**Issue by mqzhanglab** [idekerlab/DrugCell#10]
For GPU based python 3.6.9. google colab

It will report error in last line(train_model) train_drugcell.py for the line 177 of drugcell_NN.py
Something about the root:

final_input = torch.cat((term_NN_out_map[self.root], drug_out), 1)

[
<img width="1069" alt="Screen Shot 2021-01-10 at 6 17 54 PM" src="https://user-images.githubusercontent.com/46196207/104138185-80f64d80-5370-11eb-81b9-4ee5a34ad9bc.png">
](url)

**Comment by Sepstar** [comment]
I had the same problem. For me, the problem is that self.term_layer_list is not generated. So in the function: construct_NN_graph(self, dG), I add 'return self.term_layer_list' at last. And I changed self.term_layer_list = self.construct_NN_graph(dG)  in the def __init__().

**Comment by jisoopark** [comment]
Hi,

Can you try to run the script on the command line and let me whether it still fails? Did you run all the functions in the "main" function (not specifically defined but placed after the train_drugcell function)?. I am little puzzled about the error because your ontology seems loaded correctly - there might be a problem in the initialization of term_NN_out_map.

Thanks,
Jisoo
