### ISSUE TITLE
Resource Guide Missing

### ISSUE THREAD

**Issue by DarioS** [idekerlab/DrugCell#12]
I plan to run this software on a HPC with PBS Professional scheduler and I need to specify resources in the PBS script. It would be handy to have a resource guide in the documentation. For example, my whole genome DNA-seq structural variant analysis has:

```
#!/bin/bash
#PBS -l ncpus=8
#PBS -l mem=80GB
#PBS -l walltime=14:00:00
```

What would suitable values be for DrugCell training? For testing? How do these values change as the input data size changes?

```
#PBS -l ngpus=<x>
```

How many GPUs can the software take advantage of and what should `<x>` be replaced by?

**Comment by jisoopark** [comment]
Hi, 

I figure that the problem with you was not really about resources but more about the environment set up. After trying to set up your environment without conda and run the script again, please reach out back to us if the problem persists. Thanks.

Jisoo

**Comment by DarioS** [comment]
No, it's completely separate to that. On a shared H.P.C., it is mandatory to specify the RAM, CPU and GPU and running time **before** executing the analysis. If the analysis uses more resources than was specified by the job script, it will be terminated immediately by the scheduling system. So, it would be good to have a guide explaining the resource requirements of (1) model training and (2) prediction. It is quite different to using a standalone server. An introduction to such servers can be seen [here](https://sydney-informatics-hub.github.io/training.artemis.introhpc/03-pbs-scripts/index.html).

**Comment by jisoopark** [comment]
What I meant is that you will have to figure those out at your end based on the specification of the nodes in the cluster. I called it related to "the environment", because you were unable to run the training script and figure out the running time specific to your data and your cluster. 

I suggest you first establish the software environment to be able to run the training script, then play with some parameters depending on your cluster node specification. For example, you can reduce the batch size to reduce the GPU memory required to train the model when you get out of memory error, etc. Hope this helps.
