### ISSUE TITLE
Use predict_drugcell_cpu.py to predict drug response but meet KeyError: 'C1CC1COC\\2=CC=CC(=O)/C2=C\\3/C=C(C(=C(N3)N)C'

### ISSUE THREAD

**Issue by sjtudw** [idekerlab/DrugCell#4]
I prepared the following files:
1.LIVER_id.txt 
0	SNU182_LIVER
1	HLE_LIVER
2	HLF_LIVER

2.HCCcell_mutation.txt
I took a subset of the cell2mutation.txt 
26 rows of  HCC cells , 3008 colnums of genes

3.test_data.txt 
The 1st column is identification of 26 HCC cells, the 2nd column is identification of drugs from drug2ind.txt and the 3rd column is the dummy values.

other files or text are used in DrugCell/data without any operations.
 Then, i performed the following command:
python /home/data/vip32/DrugCell/DrugCell/code/predict_drugcell_cpu.py -gene2id  /home/data/vip32/DrugCell/DrugCell/data/gene2ind.txt -cell2id /home/data/vip32/DrugCell/DrugCell/HCC_data/LIVER_id.txt -drug2id /home/data/vip32/DrugCell/DrugCell/data/drug2ind.txt -genotype /home/data/vip32/DrugCell/DrugCell/HCC_data/HCCcell_mutation.txt -fingerprint /home/data/vip32/DrugCell/DrugCell/data/drug2fingerprint.txt -predict /home/data/vip32/DrugCell/DrugCell/HCC_data/test_data.txt -hidden /home/data/vip32/DrugCell/DrugCell/hidden -result /home/data/vip32/DrugCell/DrugCell/result -load /home/data/vip32/DrugCell/DrugCell/load/drugcell_v1.pt

and some erro occur:
/home/data/vip32/DrugCell/DrugCell/HCC_data/test_data.txt
Traceback (most recent call last):
  File "/home/data/vip32/DrugCell/DrugCell/code/predict_drugcell_cpu.py", line 81, in <module>
    predict_data, cell2id_mapping, drug2id_mapping = prepare_predict_data(opt.predict, opt.cell2id, opt.drug2id)
  File "/home/data/vip32/DrugCell/DrugCell/code/util.py", line 105, in prepare_predict_data
    test_feature, test_label = load_train_data(test_file, cell2id_mapping, drug2id_mapping)
  File "/home/data/vip32/DrugCell/DrugCell/code/util.py", line 93, in load_train_data
    feature.append([cell2id[tokens[0]], drug2id[tokens[1]]])
KeyError: 'C1CC1COC\\2=CC=CC(=O)/C2=C\\3/C=C(C(=C(N3)N)C'

I also found that these identification of drugs did not exist in provided drugcell_test.txt

I appreciate your help.
Thanks, 
Wei

**Comment by jisoopark** [comment]
Thanks for your interest in using our model.

The error occurs because the drug2ind.txt file should also have your drug information. Specifically, for the SMILES representation, "C1CC1COC\2=CC=CC(=O)/C2=C\3/C=C(C(=C(N3)N)C", your drug2ind.txt should look like this:

0    C1CC1COC\2=CC=CC(=O)/C2=C\3/C=C(C(=C(N3)N)C

In addition, your drug2fingerprint.txt file should have the Morgan fingerprint calculated for your SMILES representation using the rdkit package. I just tried to generate the morgan fingerprint for your SMILES representation, but it gives me an error because not all opening parentheses ('(') are paired with closing parentheses (')'). So, please check your SMILES representation before proceeding again. 

Thanks!
